In [19]:
#x=[randn(3,2)*.4;randn(4,2)*.5+ones(4,1)*[4 4]]
import numpy as np
a = np.random.randn(3,2)*.4
b = np.random.randn(4,2)*.5
c = np.ones((4,1))*[4,4]
d = [a,b+c]
d

SyntaxError: invalid syntax (<ipython-input-19-51d5928a7f94>, line 6)

In [45]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print type(a)
print a[:,np.newaxis].dot(a[np.newaxis,:])
print np.sqrt(sum(np.power(b-a,2)))
print type(np.mat(np.zeros((2, 2))))
print type(np.zeros((2, 2)))

<type 'numpy.ndarray'>
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
8.0
<class 'numpy.matrixlib.defmatrix.matrix'>
<type 'numpy.ndarray'>


In [15]:
from numpy import * 
a = random.uniform(0,10)
print a,int(a)
data = array([[1,2,3],[4,5,6],[7,8,9]])
print data[0,:]

5.06057078862 5
[1 2 3]
