In [7]:
import numpy as np
#一维数组
a = np.array([2, 0, 1, 5, 8, 3])
print u'原始数据:', a
print u'最小值:', a.min()
print u'最大值:', a.max()
print u'形状', a.shape
# [:-2]从后往前，除了后面两个元素
print a[:-2]
#[-2:]表示从后往前获取两个元素
print a[-2:]
#[:1]表示从头开始获取，获取1个元素
print a[:1]
#[1:]表示从头开始获取，除了第1个元素
print a[1:]
# 排序
print type(a)
print a.dtype
a.sort()
print u'排序后:', a

原始数据: [2 0 1 5 8 3]
最小值: 0
最大值: 8
形状 (6L,)
[2 0 1 5]
[8 3]
[2]
[0 1 5 8 3]
<type 'numpy.ndarray'>
int32
排序后: [0 1 2 3 5 8]


In [11]:
#二维数组
c = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])

# 获取值
print u'形状:', c.shape
print u'获取值:', c[1][0]
print u'获取某行:'
print c[1][:]
print u'获取某行并切片:'
print c[0][:-1]
print c[0][-1:]

#获取具体某列值
print u'获取第3列:'
#np.newaxis增加一个新维度
print c[:,np.newaxis, 2]
print c[:, 2]
#函数
#sin
print np.sin(np.pi/6)
print np.sin(np.pi/2)
print np.tan(np.pi/2)
print np.pi
print np.arange(0,4)

形状: (3L, 4L)
获取值: 4
获取某行:
[4 5 6 7]
获取某行并切片:
[1 2 3]
[4]
获取第3列:
[[3]
 [6]
 [9]]
[3 6 9]
0.5
1.0
1.63312393532e+16
3.14159265359
[0 1 2 3]


In [26]:
import numpy as np  
import matplotlib.pyplot as plt  
'''
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
也就是说在从0到10(包含0和10)之间均匀的生成1000个样本
endpoint:是否包含stop
retstep:是否显示步长
'''  
x = np.linspace(0, 10, 1000,endpoint=False,retstep=True,dtype=np.float64)
'''
numpy.arange([start, ]stop, [step, ]dtype=None)
start:可以没有，默认是0，包含start
end:必须有，不包含end
step:可以不写，默认是1
'''
a = np.arange(0,10)
'''
random的参数必须是一个元组 表示形状
'''
b = np.random.random((5,5))
'''
等价于np.random.random((5,4))
'''
c = np.random.rand(5,4)
'''
[0-4]之间的整数，不包括4，low从0开始 
区别random_integers的low是从1开始
'''
d = np.random.randint(4,size=(3,2))
'''
标准正太分布
'''
e = np.random.randn(4,4)

array([[ 1.5421589 ,  1.62306741,  1.1282769 , -2.96313049],
       [ 0.42099945, -1.60361111,  2.15287123,  0.35297224],
       [ 0.49068878, -1.29749764, -1.55672112,  0.78702108],
       [ 0.01815955, -1.94300652,  0.95054118, -1.09586137]])

In [13]:
import numpy as np
z = np.arange(1,101)
a = np.arange(9).reshape(3,3)  
np.dot(np.ones((5,3)),np.ones((3,2)))
b = np.random.random((5,5))  
# print str(b.max()) +' '+ str(b.min())
c = (b - b.min())/(b.max() - b.min())
#linspace(start, stop, num=50, endpoint=True, retstep=False)
#生成0~10之间均匀分布的11个数，包括0和1。
#endpoint=False,则10不包括在里面。
#retstep=False，会同时返回均匀区间中每两个数的间隔。
d = np.linspace(0,10,11,endpoint=True, retstep=True)
e = np.random.random(10)
print e
f = sorted(e,reverse=True)
print f
#randint(min,max,num)生成大小为num的array，数值范围min～max
A = np.random.randint(0,2,5)  
B = np.random.randint(0,2,5)  
#判断两个array在误差范围内是否相等。函数原型allclose(a, b, rtol=1e-05, atol=1e-08)，若absolute(a - b) <= (atol + rtol * absolute(b))则相等
equal = np.allclose(A,B)  
print A.dtype

[ 0.88850406  0.7777672   0.71509201  0.72492478  0.45724216  0.74287312
  0.93471545  0.72139224  0.82843694  0.37749591]
[0.93471544880761215, 0.88850405521756803, 0.82843694342560326, 0.77776719916703818, 0.74287312157373997, 0.72492477955771684, 0.7213922413108802, 0.71509200791469463, 0.45724216430491471, 0.37749591431245566]
int32


In [4]:
import numpy as np
a = np.array([[1,0,2,3],[3,2,0,1]])
mask = np.zeros(a.shape, dtype=bool)
b = np.argsort(a,kind="mergesort")[-2:]
print a
print b
print mask
mask[[(0,1),(1,1)]] = 1
print mask
import numpy as np
a = np.array([1,0,3,2])
mask = np.zeros(a.shape, dtype=bool)
b = np.argsort(a,kind="mergesort")[-2:]
print b
print mask
mask[b] = 1
print mask

[[1 0 2 3]
 [3 2 0 1]]
[[1 0 2 3]
 [2 3 1 0]]
[[False False False False]
 [False False False False]]
[[False  True False False]
 [False  True False False]]
[3 2]
[False False False False]
[False False  True  True]
