In [7]:
import numpy as np
#一维数组
a = np.array([2, 0, 1, 5, 8, 3])
print u'原始数据:', a
print u'最小值:', a.min()
print u'最大值:', a.max()
print u'形状', a.shape
# [:-2]从后往前，除了后面两个元素
print a[:-2]
#[-2:]表示从后往前获取两个元素
print a[-2:]
#[:1]表示从头开始获取，获取1个元素
print a[:1]
#[1:]表示从头开始获取，除了第1个元素
print a[1:]
# 排序
print type(a)
print a.dtype
a.sort()
print u'排序后:', a

原始数据: [2 0 1 5 8 3]
最小值: 0
最大值: 8
形状 (6L,)
[2 0 1 5]
[8 3]
[2]
[0 1 5 8 3]
<type 'numpy.ndarray'>
int32
排序后: [0 1 2 3 5 8]


In [11]:
#二维数组
c = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10]])

# 获取值
print u'形状:', c.shape
print u'获取值:', c[1][0]
print u'获取某行:'
print c[1][:]
print u'获取某行并切片:'
print c[0][:-1]
print c[0][-1:]

#获取具体某列值
print u'获取第3列:'
#np.newaxis增加一个新维度
print c[:,np.newaxis, 2]
print c[:, 2]
#函数
#sin
print np.sin(np.pi/6)
print np.sin(np.pi/2)
print np.tan(np.pi/2)
print np.pi
print np.arange(0,4)

形状: (3L, 4L)
获取值: 4
获取某行:
[4 5 6 7]
获取某行并切片:
[1 2 3]
[4]
获取第3列:
[[3]
 [6]
 [9]]
[3 6 9]
0.5
1.0
1.63312393532e+16
3.14159265359
[0 1 2 3]


In [14]:
import numpy as np  
import matplotlib.pyplot as plt  
'''
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
也就是说在从0到10(包含0和10)之间均匀的生成1000个样本
endpoint:是否包含stop
retstep:是否显示步长
'''  
x = np.linspace(0, 10, 1000,endpoint=False,retstep=True,dtype=np.float64)
'''
numpy.arange([start, ]stop, [step, ]dtype=None)
start:可以没有，默认是0，包含start
end:必须有，不包含end
step:可以不写，默认是1
'''
a = np.arange(0,10)


array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])