In [9]:
# encoding: utf-8
import numpy as np
from scipy import linalg
arr = np.array([[1,2],[3,4]])
print arr
##矩阵行列式
print "矩阵行列式：",linalg.det(arr)
print "矩阵的逆：",linalg.inv(arr)

[[1 2]
 [3 4]]
矩阵行列式： -2.0
矩阵的逆： [[-2.   1. ]
 [ 1.5 -0.5]]


In [1]:
import numpy as np
from scipy import *
from scipy.sparse import csr_matrix
row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
a = csr_matrix((data, (row, col)), shape=(3, 3)).toarray()
print a
print a[:1,:-1]

[[1 0 2]
 [0 0 3]
 [4 5 6]]
[[1 0]]
